title: Fitcloak
description: A lightweight local preview server for developing native Keycloak FreeMarker themes
baseurl: ""

remote_theme: just-the-docs/just-the-docs

logo: /assets/images/logo.svg

search_enabled: true
heading_anchors: true

aux_links:
  GitHub: https://github.com/msotnikov/fitcloak
aux_links_new_tab: true

nav_sort: order

# Google Analytics 4
ga_measurement_id: G-2V3FVH3R0C

footer_content: >-
  Fitcloak is licensed under the <a href="https://github.com/msotnikov/fitcloak/blob/main/LICENSE">MIT License</a>.
